"""The surfaces Godot puts on a Machine, checked against the palette they come from.

Seam: the committed files — `tools/assets/dieselpunk_palette.json`, the
`.tres` resources under `assets/machines/materials/`, and the `_subresources`
override in each `assets/machines/*.glb.import`. These are generated by
`tools/assets/machine_materials.py --write`, and generated files that nobody
re-runs are how a declaration and the thing it declares drift apart, so the
suite re-derives them and fails on any difference.
"""

import json
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import gltf_info  # noqa: E402
import machine_materials  # noqa: E402
import machine_specs  # noqa: E402

REPO = Path(__file__).resolve().parents[3]


class ThePaletteSurfaces(unittest.TestCase):
    def setUp(self) -> None:
        self.entries = machine_materials.load()

    def test_names_only_textures_that_were_generated(self):
        """A palette naming a map nobody generated is a Machine that renders
        untextured in the engine and perfectly fine in every byte-level test."""
        self.assertEqual(machine_materials.missing_textures(), [])

    def test_gives_every_textured_material_a_size_in_metres(self):
        """`texture_scale_m` is the only thing that sets texture density, because
        the meshes are UV'd at world scale. A texture without one has no size."""
        for entry in self.entries:
            if not entry.get("texture"):
                continue
            with self.subTest(material=entry["name"]):
                self.assertGreater(entry.get("texture_scale_m", 0), 0.0)
                self.assertLess(entry["texture_scale_m"], 8.0,
                                "one tile wider than a Machine is not a tiling texture")

    def test_leaves_only_the_smallest_fittings_untextured(self):
        """Going untextured is a decision about render cost on parts a player
        sees as a coloured dot, so it stays a short, named list rather than a
        drift."""
        bare = sorted(e["name"] for e in self.entries if not e.get("texture"))
        self.assertEqual(bare, ["Copper", "DullBrass", "GaugeGlass"])


class TheGodotMaterials(unittest.TestCase):
    def test_exist_for_every_palette_entry_and_for_nothing_else(self):
        declared = {f"{e['name']}.tres" for e in machine_materials.load()}
        written = {p.name for p in machine_materials.MATERIAL_DIR.glob("*.tres")}
        self.assertEqual(written, declared)

    def test_are_exactly_what_the_palette_generates(self):
        """Re-derive and compare. A hand-edit to a `.tres` is a second authority
        on what a Machine looks like, and this is what stops one existing."""
        for entry in machine_materials.load():
            destination = machine_materials.MATERIAL_DIR / f"{entry['name']}.tres"
            with self.subTest(material=entry["name"]):
                self.assertEqual(destination.read_text(),
                                 machine_materials.godot_resource(entry),
                                 "run tools/assets/machine_materials.py --write")

    def test_are_wired_onto_every_machine_mesh(self):
        """The mechanism that actually applies a texture to a Machine: the glTF
        material is a palette *name* and the importer substitutes the shared
        material for it. A mesh missing the override renders flat-shaded."""
        names = [e["name"] for e in machine_materials.load()]
        for machine in machine_specs.load():
            sidecar = machine_materials.MACHINE_DIR / f"{machine.machine_id}.glb.import"
            with self.subTest(machine=machine.machine_id):
                self.assertTrue(sidecar.exists(),
                                "no .glb.import — let Godot import the mesh first")
                text = sidecar.read_text()
                overrides = machine_materials.declared_overrides(text)
                used = set(gltf_info.material_names(
                    gltf_info.read_gltf_json(
                        machine_materials.MACHINE_DIR / f"{machine.machine_id}.glb")))
                self.assertTrue(used, "the mesh names no materials at all")
                for name in sorted(used):
                    self.assertEqual(overrides.get(name),
                                     f"{machine_materials.GODOT_MATERIAL_DIR}/{name}.tres",
                                     f"{name} would render flat-shaded")
                self.assertEqual(
                    machine_materials.patch_import_sidecar(text, names), text,
                    "run tools/assets/machine_materials.py --write")

    def test_point_at_textures_by_the_uid_godot_assigned(self):
        """Godot resolves a resource by uid and keeps the path as a fallback, so
        a `.tres` citing only the path is rewritten the first time the editor
        opens it — which would make these generated files churn forever."""
        for entry in machine_materials.load():
            path = machine_materials.texture_path(entry)
            if path is None:
                continue
            body = (machine_materials.MATERIAL_DIR / f"{entry['name']}.tres").read_text()
            sidecar = path.with_suffix(".png.import").read_text()
            uid = next(line for line in sidecar.splitlines()
                       if line.startswith("uid=")).split('"')[1]
            with self.subTest(material=entry["name"]):
                self.assertIn(uid, body)


class TheTextureImportSettings(unittest.TestCase):
    """The generated textures were imported by #20 as 2D images. A tiled surface
    on a Machine seen at a grazing angle across a Factory needs mipmaps, or it
    shimmers; and Godot's `detect_3d` would otherwise rewrite these sidecars the
    first time the game ran, dirtying the working tree from a play session."""

    def _settings(self, path: Path) -> dict[str, str]:
        return dict(line.split("=", 1) for line in path.read_text().splitlines()
                    if "=" in line and not line.startswith(("uid", "path", "source_file",
                                                            "dest_files", "importer",
                                                            "type", "metadata")))

    def test_are_set_up_for_use_on_a_mesh(self):
        for path in sorted(machine_materials.TEXTURE_DIR.glob("*.png.import")):
            with self.subTest(texture=path.name):
                settings = self._settings(path)
                self.assertEqual(settings.get("mipmaps/generate"), "true")
                self.assertEqual(settings.get("compress/mode"), "2",
                                 "VRAM compressed, not stored raw")
                self.assertEqual(settings.get("detect_3d/compress_to"), "0",
                                 "already configured, so the engine must not "
                                 "rewrite this file at run time")


class TheManifestFromTheGenerator(unittest.TestCase):
    def test_every_texture_the_palette_uses_is_one_tools_aigen_can_reproduce(self):
        """#20's claim is that every committed image can be regenerated from a
        committed recipe. Wearing one on a Machine is only safe while that holds,
        so the palette may only name maps the manifest records."""
        manifest = json.loads(
            (REPO / "assets" / "generated" / "textures" / "manifest.json").read_text())
        reproducible = {record["id"] for record in manifest["records"]}
        used = {e["texture"] for e in machine_materials.load() if e.get("texture")}
        self.assertEqual(used - reproducible, set())


if __name__ == "__main__":
    unittest.main()
